[general]
import = ["~/.config/alacritty/matugen.toml"]

[terminal.shell]
program = "/usr/bin/zsh"

[font]
size = 11.3

[font.normal]
family = "JetBrains Mono"
style = "Bold"

[window]
opacity = 0.70
padding = { x = 6, y = 6 }

[keyboard]
bindings = [
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]
