[terminal.shell]
program = "/usr/bin/zsh"

[font]
size = 11.3
#test
[font.normal]
family = "JetBrains Mono"
style = "Bold"

[window]
opacity = 0.80
padding = { x = 6, y = 6 }

[colors.primary]
background = "#181818"
foreground = "#d8d8d8"

[keyboard]
bindings = [
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]
